### ISSUE TITLE
We should be able to start FMKe in a more idiomatic way

### ISSUE THREAD

**Issue by goncalotomas** [goncalotomas/FMKe#121]
Instead of using lots of magic from the config files, etc, maybe it would be beneficial to include a `start/3` that would take in the list of IPs and ports to connect to, as well as the target system. This would make it easier for users, since they wouldn't even have to edit config files.

**Comment by bieniusa** [comment]
This is a bad idea: coding the values into the program requires recompiling the program every time something is changed. 
Plus, you need to look at program code to configure the benchmark.

People do not like it. Please do not do this, we will have to revert it.

**Comment by goncalotomas** [comment]
@bieniusa I think my suggestion might have been better explained.

I like having a configuration file as we do right now so that it is easy to deploy, and I don't intend to remove that feature, I agree that woudn't make sense to do it. I propose the following:

Let's say that you cloned the repository and ran `rebar3 release` to generate a release. You'd still be able to use FMKe with the existing configuration file, no changes would be made.

But, if you try to use FMKe in a more interactive way, such as running a simple `erl -pa _build/default/*/ebin`, you cannot start FMKe as is. What I propose is to add some logic, as described above, that would allow you to have a simple interactive session like the following:

```bash
$ docker run -d --name riak -p "8087:8087" -p "8098:8098" -e NODE_NAME=riak@127.0.0.1 goncalotomas/riak
0123456789abcdef
$ docker run -d --name redis -p "6379:6379" redis
0123456789abcdee
$ erl -pa _build/default/*/ebin
Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
```

```erlang
1> fmke:start(riak, [{localhost, 8087}]).
ok
2> fmke:create_patient(1, "Gonçalo", "Portugal").
ok
3> fmke:get_patient_by_id(1).
{patient, <<"Gonçalo">>, <<"Portugal">>, []}
4> fmke:stop().
ok
5> fmke:start(redis, [{localhost, 6379}]).
ok
6> fmke:create_patient(1, "Gonçalo", "Portugal).
ok
[...]
```
I think this would be a cool way to interact with FMKe if you were just trying it out. My idea was to merely add support for this, I did not intend for this to become the main way of interacting.

I feel like things are a little clearer now, and given this example interaction I see no need to look at program code in order to be able to configure the benchmark or recompiling things. What are your thoughts on this?

**Comment by bieniusa** [comment]
Thanks for the clarification!
This seems sensible indeed.

**Comment by goncalotomas** [comment]
Since #185, it is now possible to run `application:ensure_all_started(fmke).`, provided the options have been defined in OS environment variables, or application environment variables have been defined in the shell

```erl-sh
1> net_kernel:start(['fmke@127.0.0.1', longnames]).
{ok,<0.66.0>}
(fmke@127.0.0.1)2> application:set_env(fmke, target_database, redis).
ok
(fmke@127.0.0.1)3> application:set_env(fmke, database_addresses, ["127.0.0.1"]).
ok
(fmke@127.0.0.1)4> application:set_env(fmke, database_ports, [6379]).
ok
(fmke@127.0.0.1)5> application:ensure_all_started(fmke).
14:58:44.185 [info] Application lager started on node 'fmke@127.0.0.1'
14:58:44.195 [info] Application crypto started on node 'fmke@127.0.0.1'
14:58:44.197 [info] Application cowlib started on node 'fmke@127.0.0.1'
14:58:44.217 [info] Application asn1 started on node 'fmke@127.0.0.1'
14:58:44.217 [info] Application public_key started on node 'fmke@127.0.0.1'
14:58:44.244 [info] Application ssl started on node 'fmke@127.0.0.1'
14:58:44.246 [info] Application ranch started on node 'fmke@127.0.0.1'
14:58:44.249 [info] Application cowboy started on node 'fmke@127.0.0.1'
14:58:44.250 [info] Application jsx started on node 'fmke@127.0.0.1'
14:58:44.252 [info] Application antidote_pb started on node 'fmke@127.0.0.1'
14:58:44.253 [info] Application protobuffs started on node 'fmke@127.0.0.1'
14:58:44.253 [info] Application riak_pb started on node 'fmke@127.0.0.1'
14:58:44.254 [info] Application riak_client started on node 'fmke@127.0.0.1'
14:58:44.256 [info] Application eredis started on node 'fmke@127.0.0.1'
14:58:44.259 [info] fmke option 'adapter' read from defaults, set to fmke_ndm_adapter
14:58:44.259 [info] fmke option 'connection_pool_size' read from config_file, set to 64
14:58:44.259 [info] fmke option 'database_addresses' read from app_env, set to ["127.0.0.1"]
14:58:44.259 [info] fmke option 'database_ports' read from app_env, set to [6379]
14:58:44.259 [info] fmke option 'http_port' read from config_file, set to 9090
14:58:44.260 [info] fmke option 'target_database' read from app_env, set to redis
14:58:44.260 [info] Generating spec for conn pool with name pool_127_0_0_1
14:58:44.289 [info] Application fmke started on node 'fmke@127.0.0.1'
{ok,[poolboy,syntax_tools,compiler,goldrush,lager,crypto,
     cowlib,asn1,public_key,ssl,ranch,cowboy,jsx,antidote_pb,
     protobuffs,riak_pb,riak_client,eredis,fmke]}
```

After booting, it is possible to call `application:stop(fmke)`, redefine the variables and restart the application using the same strategy.
