### ISSUE TITLE
Redis shows decreased throughput over time

### ISSUE THREAD

**Issue by goncalotomas** [goncalotomas/FMKe#166]
We should re-implement the driver using the new interface to fix it.

**Comment by eduardofcbg** [comment]
Please fix this. I rely on this software.

**Comment by goncalotomas** [comment]
This is related to #182. The current ordinary redis driver is being used through `fmke_kv_driver` which (incorrectly) has some nested data model logic associated with it. If the interface of `fmke_db_driver_redis` is generic enough, then we may choose to use a future `fmke_kv_normalized_adapter` that would fix this.

Closing, since fixing #182 will fix this as well.
