### ISSUE TITLE
Intermittent compilation issues with Cassandra Driver

### ISSUE THREAD

**Issue by goncalotomas** [goncalotomas/FMKe#221]
We use `erlcass` as a dependency for connecting with Cassandra. At the time of the implementation, it was a stable driver, but it still required some contrived steps of installing further dependencies and compiling C/C++ code. Over time it seems to be [having problems with the latest releases of gcc](https://github.com/silviucpp/erlcass/issues/45), and I had some trouble setting it up again.

To be clear, this issue might not have such a big impact on linux systems, but in macOS there are constant build problems in C/C++ projects every time that a new version such as Big Sur is released.

It's bad when FMKe breaks because one of it's drivers is having some issues, so it would probably be wise to move to something like [cqerl](https://github.com/cqerl/cqerl). Hopefully, by using a pure Erlang version we won't have as many issues of this type, but this would imply rewriting some parts of the Cassandra driver. The fact that most of the compile time is spent on `erlcass` does not help either.

There is also an argument to be made when comparing benchmarks of different databases when they are not all implemented in pure Erlang, so this would be another reason to move to `cqerl` that is not stability related.

**Comment by silviucpp** [comment]
Hello, last erlcass compiles on GCC9 as well. I added in travis more environments to make sure we cover last distributions as well.
