### ISSUE TITLE
Serializing nested maps to JSON

### ISSUE THREAD

**Issue by goncalotomas** [goncalotomas/FMKe#32]
`fmk_core:get_patient_by_id(X)` returns a result which is not easily parsable by the two JSON encoders I found for Erlang. Since a GET to `patients/patient_id` should return all patient information including nested fields like prescriptions, treatments and events, I need to find a way to serialise the antidote results to JSON in order to later return them in the HTTP endpoint.

**Comment by goncalotomas** [comment]
@peterzeller Would you happen to know how I could achieve this?
For example, here is a result of calling `fmk_core:get_patient_by_id`:
```erlang
[{{<<"patient_address">>,antidote_crdt_lwwreg},
  <<131,107,0,28,78,101,119,32,72,97,109,112,115,104,105,
    114,101,44,32,85,110,105,116,101,100,32,...>>},
 {{<<"patient_id">>,antidote_crdt_counter},5000},
 {{<<"patient_name">>,antidote_crdt_lwwreg},
  <<131,107,0,12,80,104,105,110,101,97,115,32,71,97,103,101>>},
 {{<<"patient_prescriptions">>,antidote_crdt_gmap},
  [{{<<"prescription_591282">>,antidote_crdt_gmap},
    [{{<<"prescription_date_prescribed">>,antidote_crdt_lwwreg},
      <<131,107,0,8,49,47,49,47,50,48,49,54>>},
     {{<<"prescription_drugs">>,antidote_crdt_orset},
      [<<131,107,0,8,65,100,100,101,114,97,108,108>>,
       <<131,107,0,13,65,109,105,116,114,105,112,116,121,108,
         ...>>]},
     {{<<"prescription_facility_id">>,antidote_crdt_counter},20},
     {{<<"prescription_id">>,antidote_crdt_counter},591282},
     {{<<"prescription_pharmacy_id">>,antidote_crdt_counter},225},
     {{<<"prescription_prescriber_id">>,antidote_crdt_counter},
      154}]}]}]
```

How could I completely serialise this object to JSON?

**Comment by peterzeller** [comment]
Seems there are two problems: 

1. The keys are pairs consisting of a name and a type. You could go over the result recursively and remove all the types from the keys (assuming the names are unique).
2. Some binaries in there are probably not encodable as string (the ones starting with `131,107,0`). This happens if you call `term_to_binary` on a string. You could use `list_to_binary` instead, e.g.:

    ```
    3> list_to_binary("hello world").
    <<"hello world">>
    4> term_to_binary("hello world").
    <<131,107,0,11,104,101,108,108,111,32,119,111,114,108,100>>
    ```

    Alternatively you could go over the result recursively and replace all the values with `binary_to_term` of that value.

We can talk on Slack if it's not clear what I mean here.
