### ISSUE TITLE
cowlib dependency compile error

### ISSUE THREAD

**Issue by Maryam81609** [goncalotomas/FMKe#45]
Hi,

I am trying to build a release from scratch (just cloned), cowlib compilation fails.

```
===> Compiling cowlib
===> Compiling _build/default/lib/cowlib/src/cow_sse.erl failed
_build/default/lib/cowlib/src/cow_sse.erl:32: syntax error before: ':='

_build/default/lib/cowlib/src/cow_sse.erl:44: type event() undefined

make: *** [compile] Error 1
```

Thanks,
Maryam

**Comment by goncalotomas** [comment]
Hello Maryam!

`cowlib` is the required dependency for exposing an HTTP interface for FMKe operations. It has not given me any issues before, so can you provide me some more information about your environment?

Specifically, what OTP version are you working with? I've tested FMKe with OTP 18 and 19, so there shouldn't be any issues with those versions, but if that's not what you're running then I can try to help debug the issue.

Thanks,

**Comment by Maryam81609** [comment]
Thank you Goncalo!

I was building FMKe on Ubuntu 14.04 amd64, with OTP 18.3. 

I solved the issue by installing OTP 19. 

I could use maps that are supported by Erlang 18.3 as well, but for some reason that I am not aware of, building FMKe with OTP 18.3 did not work form.

Thanks!

**Comment by goncalotomas** [comment]
Great to know you're managing with OTP 19 😀

Please don't hesitate to open the issue again if there are other issues compiling dependencies.
