### ISSUE TITLE
Is it possible to set the KV_IMPLEMENTATION macro dynamically?

### ISSUE THREAD

**Issue by Maryam81609** [goncalotomas/FMKe#99]
When using Antidote, the following line in `fmk.hrl` results in {tcp,econnrefused} error:

```Erlang
-define(KV_IMPLEMENTATION, fmke_db_driver_riak_kv).
```
Thanks,
Maryam

**Comment by goncalotomas** [comment]
When using antidote that line is incorrect. This is one of the changes that is performed by the `set_target_data_store.sh` script. Are you calling that script before running FMKe?

The `{tcp,econnrefused}` error should only appear in two cases:

1. No antidote node is launched and FMKe fails to connect to the backend.
2. An antidote node is already running and you are using a script that tries to launch a new antidote instance.

Can you provide any details about these two cases?

If you want to use Antidote you should have in the `fmk.hrl` file:

```erlang
-define(KV_IMPLEMENTATION, fmke_db_driver_antidote).
```

Again, this can be changed by calling the `set_target_data_store.sh` script.

**Comment by Maryam81609** [comment]
Thanks Gonçalo!

I have updated fmk.hrl as you said:
```Erlang
-define(KV_IMPLEMENTATION, fmke_db_driver_antidote).
```
And this works fine. I was looking for a way to do this automatically. Could you please guide me where the script `set_target_data_store.sh` is located? It is not under scripts subdirectory.

**Comment by goncalotomas** [comment]
It is in `scripts/config/set_target_data_store.sh`.

Since this solves your issue, I'm going to mark this as solved. :)
